import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;

public class ModifyAccountPage extends javax.swing.JFrame implements ActionListener {

    public ModifyAccountPage() {
        setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        PicturejPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UsernamejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Addressline2jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EmailTextField2 = new javax.swing.JTextField();
        Addressline1jTextField2 = new javax.swing.JTextField();
        ContactjTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        UserIDjTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        Addressline3jTextField3 = new javax.swing.JTextField();
        EmailjLabel = new javax.swing.JLabel();
        NamejTextField4 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PasswordjTextField1 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        ConfirmPasswordjTextField1 = new javax.swing.JPasswordField();
        PasswordjPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        SavejButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 51, 0));
        jLabel16.setText("Modify Account");

        PicturejPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PicturejPanelLayout = new javax.swing.GroupLayout(PicturejPanel);
        PicturejPanel.setLayout(PicturejPanelLayout);
        PicturejPanelLayout.setHorizontalGroup(
                PicturejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 170, Short.MAX_VALUE)
        );
        PicturejPanelLayout.setVerticalGroup(
                PicturejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 197, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Username:");

        UsernamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernamejTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setText("     Personal Information");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("Address:");

        Addressline2jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addressline2jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setText("Gender:");

        EmailTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextField2ActionPerformed(evt);
            }
        });

        Addressline1jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addressline1jTextField2ActionPerformed(evt);
            }
        });

        ContactjTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactjTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setText("UserType:");

        jComboBox1.setEnabled(false);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Sales Manager", "Purchase Manager", "Inventory Manager", "Finance Manager" }));
        jComboBox1.addActionListener(this);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setText("UserID:");

        UserIDjTextField3.setText(User.generateNewId("Admin"));
        UserIDjTextField3.setEditable(false);
        UserIDjTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIDjTextField3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setText("Name:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Prefer not to say" }));

        Addressline3jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addressline3jTextField3ActionPerformed(evt);
            }
        });

        EmailjLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        EmailjLabel.setText("Email:");

        NamejTextField4.setModel(new javax.swing.DefaultComboBoxModel<>(User.generateAllNames()));
        NamejTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamejTextField4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel9.setText("Contact No: ");

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel10.setText("           Login Details");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setText("Password:");

        PasswordjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordjTextField1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel11.setText("Re-enter Password:");

        ConfirmPasswordjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordjTextField1ActionPerformed(evt);
            }
        });

        PasswordjPanel2.setBackground(new java.awt.Color(255, 102, 102));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel12.setText("Password must contain:");

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel13.setText(" 3) At least one number");

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel14.setText(" 1) Character between 6 to 20");

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel15.setText(" 2) A lower case and upper case alphabet");

        javax.swing.GroupLayout PasswordjPanel2Layout = new javax.swing.GroupLayout(PasswordjPanel2);
        PasswordjPanel2.setLayout(PasswordjPanel2Layout);
        PasswordjPanel2Layout.setHorizontalGroup(
                PasswordjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PasswordjPanel2Layout.createSequentialGroup()
                                .addGroup(PasswordjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PasswordjPanel2Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PasswordjPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel13))
                                        .addGroup(PasswordjPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel14))
                                        .addGroup(PasswordjPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel15)))
                                .addContainerGap(16, Short.MAX_VALUE))
        );
        PasswordjPanel2Layout.setVerticalGroup(
                PasswordjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PasswordjPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(EmailjLabel)
                                                        .addComponent(PicturejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                                                .addComponent(jLabel11)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                                                                .addComponent(ConfirmPasswordjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                                                                .addComponent(jLabel8)
                                                                                                .addGap(117, 117, 117))
                                                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                                .addComponent(jLabel1)
                                                                                                .addGap(115, 115, 115)))
                                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(UsernamejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                                                                                        .addComponent(PasswordjTextField1))))
                                                                .addGap(54, 54, 54)
                                                                .addComponent(PasswordjPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(51, 51, 51)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel5)
                                                                        .addComponent(jLabel7)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(jLabel3))
                                                                .addGap(37, 37, 37))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel9)
                                                                .addGap(18, 18, 18)))
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(Addressline1jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                                                                .addComponent(Addressline2jTextField1))
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(78, 78, 78)
                                                                .addComponent(jLabel6)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(UserIDjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(EmailTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Addressline3jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(NamejTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ContactjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(397, 397, 397))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PicturejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(UserIDjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(27, 27, 27)
                                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(28, 28, 28))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(NamejTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(28, 28, 28)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(EmailjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(EmailTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(32, 32, 32)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(Addressline1jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(Addressline2jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(28, 28, 28)
                                                .addComponent(Addressline3jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(43, 43, 43)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(ContactjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(UsernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(PasswordjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(21, 21, 21)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel11)
                                                        .addComponent(ConfirmPasswordjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addGap(682, 682, 682)
                                                .addComponent(PasswordjPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(99, 99, 99))
        );

        jScrollPane1.setViewportView(jPanel3);

        SavejButton.setBackground(new java.awt.Color(51, 204, 255));
        SavejButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SavejButton.setText("Save Details");
        SavejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(SavejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(17, 17, 17)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(436, 436, 436)
                                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel16)
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SavejButton, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        adminProfilePic = new JLabel();
        adminProfilePic.setBounds(0, 0, 170, 197);
        adminProfilePic.setIcon(new ImageIcon("test 3/picture/admin_pic.png"));
        adminProfilePic.setVisible(true);

        salesManagerProfilePic = new JLabel();
        salesManagerProfilePic.setBounds(0, 0, 170, 197);
        salesManagerProfilePic.setIcon(new ImageIcon("test 3/picture/sales_manager_pic.png"));
        salesManagerProfilePic.setVisible(false);

        purchaseManagerProfilePic = new JLabel();
        purchaseManagerProfilePic.setBounds(0, 0, 170, 197);
        purchaseManagerProfilePic.setIcon(new ImageIcon("test 3/picture/purchase_manager_pic.png"));
        purchaseManagerProfilePic.setVisible(false);

        inventoryManagerProfilePic = new JLabel();
        inventoryManagerProfilePic.setBounds(0, 0, 170, 197);
        inventoryManagerProfilePic.setIcon(new ImageIcon("test 3/picture/inventory_manager_pic.png"));
        inventoryManagerProfilePic.setVisible(false);

        financeManagerProfilePic = new JLabel();
        financeManagerProfilePic.setBounds(0, 0, 170, 197);
        financeManagerProfilePic.setIcon(new ImageIcon("test 3/picture/finance_manager_pic.png"));
        financeManagerProfilePic.setVisible(false);

        PicturejPanel.add(adminProfilePic);
        PicturejPanel.add(salesManagerProfilePic);
        PicturejPanel.add(purchaseManagerProfilePic);
        PicturejPanel.add(inventoryManagerProfilePic);
        PicturejPanel.add(financeManagerProfilePic);

        pack();
    }// </editor-fold>

    private void UsernamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Addressline2jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void EmailTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Addressline1jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void ContactjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void UserIDjTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Addressline3jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void NamejTextField4ActionPerformed(java.awt.event.ActionEvent evt) {
        currentUser = User.getUser(NamejTextField4.getSelectedItem().toString());

        if (currentUser instanceof SalesManager salesManager) {
            UserIDjTextField3.setText(salesManager.getSalesManagerID());
        } else if (currentUser instanceof Admin admin) {
            UserIDjTextField3.setText(admin.getAdminId());
        } else {
            UserIDjTextField3.setText("-");
        }

        jComboBox1.setSelectedItem(currentUser.getPosition());
        jComboBox2.setSelectedItem(currentUser.getGender());
        EmailTextField2.setText(currentUser.getEmail());
        Addressline1jTextField2.setText(currentUser.getAddressLine1());
        Addressline2jTextField1.setText(currentUser.getAddressLine2());
        Addressline3jTextField3.setText(currentUser.getAddressLine3());
        ContactjTextField2.setText(currentUser.getContactNo());
        UsernamejTextField.setText(currentUser.getUsername());
        PasswordjTextField1.setText(currentUser.getPassword());
        ConfirmPasswordjTextField1.setText(currentUser.getPassword());
    }

    private void PasswordjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void ConfirmPasswordjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void SavejButtonActionPerformed(java.awt.event.ActionEvent evt) {
        try {

            boolean hasUpper = false, hasLower = false, hasNum = false;
            for (char c: PasswordjTextField1.getPassword()) {
                if (Character.isUpperCase(c)) {
                    hasUpper = true;
                }
                if (Character.isLowerCase(c)) {
                    hasLower = true;
                }
                if (Character.isDigit(c)) {
                    hasNum = true;
                }
            }

            if (!User.checkUsernameAvailable(UsernamejTextField.getText()) && !currentUser.getUsername().equals(UsernamejTextField.getText())) {
                throw new NumberFormatException();

            } else if (!Arrays.equals(PasswordjTextField1.getPassword(), ConfirmPasswordjTextField1.getPassword())) {
                throw new ArithmeticException();

            } else if (PasswordjTextField1.getText().length() < 6 ||
                    PasswordjTextField1.getText().length() > 20 ||
                    !hasUpper ||
                    !hasLower ||
                    !hasNum) {
                throw new ClassNotFoundException();
            }

            String gender = jComboBox2.getSelectedItem().toString();
            String email = EmailTextField2.getText();

            String addressLine1 = Addressline1jTextField2.getText();
            String addressLine2 = Addressline2jTextField1.getText();
            String addressLine3 = Addressline3jTextField3.getText();
            String contactNo = ContactjTextField2.getText();

            String username = UsernamejTextField.getText();

            StringBuilder unedited_password = new StringBuilder();
            for (char c: PasswordjTextField1.getPassword()) {
                unedited_password.append(c);
            }
            String password = unedited_password.toString();

            currentUser.setGender(gender);
            currentUser.setEmail(email);
            currentUser.setAddressLine1(addressLine1);
            currentUser.setAddressLine2(addressLine2);
            currentUser.setAddressLine3(addressLine3);
            currentUser.setContactNo(contactNo);
            currentUser.setUsername(username);
            currentUser.setPassword(password);

            TextFileOperations.writeUserFile();
            JOptionPane.showMessageDialog(this, "Account modified successfully.");
            new AdminPage().setVisible(true);
            dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Username has been taken. Please try another one.");
        } catch (ArithmeticException e) {
            JOptionPane.showMessageDialog(this, "Passwords do not match. Please try again.");
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Password do not meet requirement. Please try again.");

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyAccountPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField Addressline1jTextField2;
    private javax.swing.JTextField Addressline2jTextField1;
    private javax.swing.JTextField Addressline3jTextField3;
    private javax.swing.JPasswordField ConfirmPasswordjTextField1;
    private javax.swing.JTextField ContactjTextField2;
    private javax.swing.JTextField EmailTextField2;
    private javax.swing.JLabel EmailjLabel;
    private javax.swing.JComboBox NamejTextField4;
    private javax.swing.JPanel PasswordjPanel2;
    private javax.swing.JPasswordField PasswordjTextField1;
    private javax.swing.JPanel PicturejPanel;
    private javax.swing.JButton SavejButton;
    private javax.swing.JTextField UserIDjTextField3;
    private javax.swing.JTextField UsernamejTextField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel adminProfilePic;
    private javax.swing.JLabel salesManagerProfilePic;
    private javax.swing.JLabel purchaseManagerProfilePic;
    private javax.swing.JLabel inventoryManagerProfilePic;
    private javax.swing.JLabel financeManagerProfilePic;
    private User currentUser;

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == jComboBox1) {
            if (jComboBox1.getSelectedItem().toString().equals("Admin")) {
                adminProfilePic.setVisible(true);
                salesManagerProfilePic.setVisible(false);
                purchaseManagerProfilePic.setVisible(false);
                inventoryManagerProfilePic.setVisible(false);
                financeManagerProfilePic.setVisible(false);
            } else if (jComboBox1.getSelectedItem().toString().equals("Sales Manager")) {
                adminProfilePic.setVisible(false);
                salesManagerProfilePic.setVisible(true);
                purchaseManagerProfilePic.setVisible(false);
                inventoryManagerProfilePic.setVisible(false);
                financeManagerProfilePic.setVisible(false);
            } else if (jComboBox1.getSelectedItem().toString().equals("Purchase Manager")) {
                adminProfilePic.setVisible(false);
                salesManagerProfilePic.setVisible(false);
                purchaseManagerProfilePic.setVisible(true);
                inventoryManagerProfilePic.setVisible(false);
                financeManagerProfilePic.setVisible(false);
            } else if (jComboBox1.getSelectedItem().toString().equals("Inventory Manager")) {
                adminProfilePic.setVisible(false);
                salesManagerProfilePic.setVisible(false);
                purchaseManagerProfilePic.setVisible(false);
                inventoryManagerProfilePic.setVisible(true);
                financeManagerProfilePic.setVisible(false);
            } else if (jComboBox1.getSelectedItem().toString().equals("Finance Manager")) {
                adminProfilePic.setVisible(false);
                salesManagerProfilePic.setVisible(false);
                purchaseManagerProfilePic.setVisible(false);
                inventoryManagerProfilePic.setVisible(false);
                financeManagerProfilePic.setVisible(true);
            }
        }
    }
    // End of variables declaration
}
